### ISSUE TITLE
Some parts cannot be translated.

### ISSUE THREAD

**Issue by coolvitto** [x64dbg/Translations#2]
1. The translation is not reflected in the "Edit columns..." context menu.
2. There is no option to translate "Dark" in the theme selection menu with X64DBG.TS.

![snp-1](https://github.com/user-attachments/assets/bee90224-2424-486c-88b8-c0ef88da7566)

![snp-2](https://github.com/user-attachments/assets/27d45658-f8c4-4b2b-a403-8d631cc60910)

**Comment by mrexodia** [comment]
For the `Edit columns...` this is probably an oversight. I think for the theme I could create a special case, but it is based on the folder name in `themes` so it makes sense that it cannot be translated.

**Comment by coolvitto** [comment]
Thank you.
I understand the theme name.
I'll look into "Edit columns..." a bit more.

**Comment by coolvitto** [comment]
In "snapshot_2024-08-26_18-37", "Edit columns..." and "Dark" were added to X64DBG.TS.
